In [1]:
import pandas as pd
import numpy as np

##### The aim of this file is to pre-process dataset including duplicates removal as well as simplification

# Read dataframe with seeating infotmation

In [2]:
industry_types = ['Cafes and Restaurants', 'Pubs, Taverns and Bars', 'Takeaway Food Services']

In [3]:
df = pd.read_csv(r"../data/Cafes_and_restaurants__with_seating_capacity .csv",usecols=["Census year", 
                                                                                            "Trading name",
                                                                                             "Industry (ANZSIC4) description",
                                                                                            "Seating type", 
                                                                                            "Number of seats", 
                                                                                            ]) 
df.columns = ["year","name", "industry","seats","num"]
df["year"] = df["year"].fillna(2019)
df_new = df[df['year'] == 2019]
df_new = df_new.fillna(" ")
df_new["seats"] = df_new["seats"].str.slice_replace(0, 8, '')
df_reset=df_new.reset_index(drop=True)

seatInfo= df_reset.loc[df_reset['industry'].isin(industry_types)]

In [4]:
seatInfo

,year,name,industry,seats,num
0,2019,Cafe Sua Da,Cafes and Restaurants,Indoor,45
1,2019,Cafe Sua Da,Cafes and Restaurants,Outdoor,6
2,2019,Brother Bull,Cafes and Restaurants,Indoor,42
3,2019,Clyde Hotel,"Pubs, Taverns and Bars",Indoor,70
4,2019,Clyde Hotel,"Pubs, Taverns and Bars",Outdoor,50
...,...,...,...,...,...
3527,2019,The Golden Triangle Restaurant,Cafes and Restaurants,Indoor,60
3528,2019,Entrecote - Paris Steakhouse & Winebar,Cafes and Restaurants,Indoor,120
3529,2019,Entrecote - Paris Steakhouse & Winebar,Cafes and Restaurants,Outdoor,30
3530,2019,Bistro Gitan,Cafes and Restaurants,Outdoor,6
3531,2019,Bistro Gitan,Cafes and Restaurants,Indoor,74

# Read raw dataframe without duplicates

In [85]:
raw = pd.read_csv(r"../data/Cafes_and_restaurants__with_seating_capacity .csv",usecols=["Census year", 
                                                                                        "Street address", 
                                                                                        "CLUE small area", 
                                                                                        "Trading name",
                                                                                        "Industry (ANZSIC4) description", 
                                                                                        "x coordinate", 
                                                                                        "y coordinate"]) 
raw.columns = ["year","address", "suburb","name", "industry","longitude","latitude"]
raw["year"] = raw["year"].fillna(2019)
raw = raw.fillna(" ")

raw2019 = raw[raw['year'] == 2019]
raw2019.drop_duplicates(subset="name", inplace = True)

<ipython-input-85-091275ed7a0a>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw2019.drop_duplicates(subset="name", inplace = True)

In [86]:
raw2019

,year,address,suburb,name,industry,longitude,latitude
47120,2019,258 Elgin Street CARLTON 3053,Carlton,Cafe Sua Da,Cafes and Restaurants,144.96553,-37.79671
47122,2019,832-834 Swanston Street CARLTON 3053,Carlton,Brother Bull,Cafes and Restaurants,144.9649,-37.79668
47123,2019,377-391 Cardigan Street CARLTON 3053,Carlton,Clyde Hotel,"Pubs, Taverns and Bars",144.96575,-37.79726
47125,2019,768-804 Swanston Street CARLTON 3053,Carlton,The Longing Flavour,Cafes and Restaurants,144.96517,-37.79783
47126,2019,768-804 Swanston Street CARLTON 3053,Carlton,Masters Of Burgerology,Cafes and Restaurants,144.96517,-37.79783
...,...,...,...,...,...,...,...
50644,2019,183 Domain Road SOUTH YARRA VIC 3141,South Yarra,Baker D Chirico,Bakery Product Manufacturing (Non-factory based),144.98213,-37.83433
50646,2019,185-189 Domain Road SOUTH YARRA VIC 3141,South Yarra,Ichi Ichi Ku Izakaya,Cafes and Restaurants,144.98226,-37.83434
50647,2019,185-189 Domain Road SOUTH YARRA VIC 3141,South Yarra,The Golden Triangle Restaurant,Cafes and Restaurants,144.98226,-37.83434
50648,2019,131-133 Domain Road SOUTH YARRA VIC 3141,South Yarra,Entrecote - Paris Steakhouse & Winebar,Cafes and Restaurants,144.98049,-37.83413
50650,2019,2-14 Hope Street SOUTH YARRA VIC 3141,South Yarra,Bistro Gitan,Cafes and Restaurants,144.97931,-37.83714

In [87]:
venu = list(raw2019['name'])
add = list(raw2019['address'])
sub = list(raw2019['suburb'])
ind = list(raw2019['industry'])
lon = list(raw2019['longitude'])
lat = list(raw2019['latitude'])

In [88]:
location_details = pd.DataFrame({"name": venu, "address": add, "suburb": sub,"industry": ind,"longitude": lon,"latitude": lat})

In [90]:
location_details['indoor'] = np.nan
location_details['outdoor'] = np.nan
location_details

,name,address,suburb,industry,longitude,latitude,indoor,outdoor
0,Cafe Sua Da,258 Elgin Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96553,-37.79671,NaN,NaN
1,Brother Bull,832-834 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.9649,-37.79668,NaN,NaN
2,Clyde Hotel,377-391 Cardigan Street CARLTON 3053,Carlton,"Pubs, Taverns and Bars",144.96575,-37.79726,NaN,NaN
3,The Longing Flavour,768-804 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96517,-37.79783,NaN,NaN
4,Masters Of Burgerology,768-804 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96517,-37.79783,NaN,NaN
...,...,...,...,...,...,...,...,...
2186,Baker D Chirico,183 Domain Road SOUTH YARRA VIC 3141,South Yarra,Bakery Product Manufacturing (Non-factory based),144.98213,-37.83433,NaN,NaN
2187,Ichi Ichi Ku Izakaya,185-189 Domain Road SOUTH YARRA VIC 3141,South Yarra,Cafes and Restaurants,144.98226,-37.83434,NaN,NaN
2188,The Golden Triangle Restaurant,185-189 Domain Road SOUTH YARRA VIC 3141,South Yarra,Cafes and Restaurants,144.98226,-37.83434,NaN,NaN
2189,Entrecote - Paris Steakhouse & Winebar,131-133 Domain Road SOUTH YARRA VIC 3141,South Yarra,Cafes and Restaurants,144.98049,-37.83413,NaN,NaN
2190,Bistro Gitan,2-14 Hope Street SOUTH YARRA VIC 3141,South Yarra,Cafes and Restaurants,144.97931,-37.83714,NaN,NaN

In [91]:
test = list(location_details['name'])

In [92]:
test.index('Little Cupcakes')

527

# Append seat infor after each venue

In [93]:
types = list(seatInfo["seats"])
num = list(seatInfo["num"])
name = list(seatInfo["name"])

name_no_dup = list(location_details["name"])

types[:10], num[:10], name[:10], name_no_dup[:10]

(['Indoor',
  'Outdoor',
  'Indoor',
  'Indoor',
  'Outdoor',
  'Indoor',
  'Indoor',
  'Outdoor',
  'Indoor',
  'Outdoor'],
 [45, 6, 42, 70, 50, 50, 50, 16, 17, 24],
 ['Cafe Sua Da',
  'Cafe Sua Da',
  'Brother Bull',
  'Clyde Hotel',
  'Clyde Hotel',
  'The Longing Flavour',
  'Masters Of Burgerology',
  'Masters Of Burgerology',
  'Wild Timor Coffee Carlton Pty Ltd',
  'Wild Timor Coffee Carlton Pty Ltd'],
 ['Cafe Sua Da',
  'Brother Bull',
  'Clyde Hotel',
  'The Longing Flavour',
  'Masters Of Burgerology',
  'Wild Timor Coffee Carlton Pty Ltd',
  'Toothpicks Cafe',
  'Claypot Kingdom',
  'E Dumpling',
  "Thresherman's Bakehouse"])

In [94]:
in_inx = []
out_inx = []
for i in range(len(types)):
    if types[i] == 'Indoor':
        in_inx.append(i)
    elif types[i] == 'Outdoor':
        out_inx.append(i)

In [95]:
for i in range(len(in_inx)):
    venue_name = name[in_inx[i]]
    no_dup_inx = name_no_dup.index(venue_name)
    location_details.loc[no_dup_inx, 'indoor'] = num[in_inx[i]]

for i in range(len(out_inx)):
    venue_name = name[out_inx[i]]
    no_dup_inx = name_no_dup.index(venue_name)
    #print(no_dup_inx, out_inx[i]    )
    location_details.loc[(no_dup_inx), 'outdoor'] = num[out_inx[i]]

In [96]:
location_details["indoor"] = location_details["indoor"].fillna(0)
location_details["outdoor"] = location_details["outdoor"].fillna(0)
location_details[:20]

,name,address,suburb,industry,longitude,latitude,indoor,outdoor
0,Cafe Sua Da,258 Elgin Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96553,-37.79671,45.0,6.0
1,Brother Bull,832-834 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.9649,-37.79668,42.0,0.0
2,Clyde Hotel,377-391 Cardigan Street CARLTON 3053,Carlton,"Pubs, Taverns and Bars",144.96575,-37.79726,70.0,50.0
3,The Longing Flavour,768-804 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96517,-37.79783,50.0,0.0
4,Masters Of Burgerology,768-804 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96517,-37.79783,50.0,16.0
5,Wild Timor Coffee Carlton Pty Ltd,249-263 Faraday Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96526,-37.79872,17.0,24.0
6,Toothpicks Cafe,714-736 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96489,-37.79947,60.0,36.0
7,Claypot Kingdom,740-750 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96476,-37.799,40.0,0.0
8,E Dumpling,740-750 Swanston Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96476,-37.799,32.0,8.0
9,Thresherman's Bakehouse,221-229 Faraday Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96673,-37.79886,70.0,50.0
10,New York Minute,235-237 Faraday Street CARLTON 3053,Carlton,Cafes and Restaurants,144.9663,-37.79881,33.0,24.0
11,Dumpling ADA,205-207 Lygon Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96656,-37.80046,35.0,16.0
12,Il Cantuccio Restaurant,209 Lygon Street CARLTON 3053,Carlton,Cafes and Restaurants,144.9666,-37.80042,100.0,20.0
13,Papa Gino's Pizza Restaurant,219-221 Lygon Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96672,-37.80019,100.0,40.0
14,Cafe Corretto,225-229 Lygon Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96674,-37.80005,60.0,55.0
15,Original Lolly Store,239 Lygon Street CARLTON 3053,Carlton,Other Specialised Food Retailing,144.96678,-37.79983,0.0,0.0
16,New Zealand Natural Ice Cream,241 Lygon Street CARLTON 3053,Carlton,Takeaway Food Services,144.96679,-37.79978,0.0,16.0
17,La Parisienne Pates,253 Lygon Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96683,-37.79954,38.0,12.0
18,University Cafe,255-257 Lygon Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96684,-37.79948,120.0,56.0
19,Lygon Food Store,263 Lygon Street CARLTON 3053,Carlton,Cafes and Restaurants,144.96687,-37.7993,29.0,45.0

In [103]:

location_details = location_details.astype(str)
location_details = location_details.astype({'indoor': int, 'outdoor': int})

location_details =location_details.convert_dtypes()

In [104]:
location_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2191 entries, 0 to 2190
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       2191 non-null   string
 1   address    2191 non-null   string
 2   suburb     2191 non-null   string
 3   industry   2191 non-null   string
 4   longitude  2191 non-null   string
 5   latitude   2191 non-null   string
 6   indoor     2191 non-null   Int32
 7   outdoor    2191 non-null   Int32
dtypes: Int32(2), string(6)
memory usage: 124.2 KB

In [105]:
#Save modified csv file to under the same folder of this notebook
location_details.to_csv(r'data_cafes_restaurants.csv', index = False, header = True)